package ipn.cic.ticketsproject;

public enum TicketStatus {

    UNKNOWN,
    CREATED,
    SETTING_STORE,
    SET_STORE,
    SETTING_TERMINAL,
    SET_TERMINAL,
    SETTING_USER,
    SET_USER,
    SETTING_PRODUCTS_COUNT,
    SET_PRODUCTS_COUNT,
    SETTING_SUBTOTAL_AMOUNT,
    SET_SUBTOTAL_AMOUNT,
    SETTING_BALANCE_AMOUNT,
    SET_BALANCE_AMOUNT,
    SETTING_TOTAL,
    SET_TOTAL,
    CERTIFICATING,
    CERTIFICATED,
    PUBLISHING,
    PUBLISHED,
    VALID,
    ERROR,
    INVALID;
    
}
